name: pro
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.24.*
  - scipy=1.10.*          
  - pandas=2.0.*         
  - matplotlib=3.7.*
  - pyyaml
  - requests
  - tqdm                  
  - einops
  - opencv                
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=12.1     
  - pip:
      - huggingface-hub==0.20.1
      - timm==0.9.2
      - wandb==0.16.1
      - pytorch-wavelets==1.3.0
      - mmengine==0.10.2
      - safetensors==0.4.3
      - transformers==4.36.2
      - torchmetrics==1.3.1
      - imageio==2.33.1
      - prettytable==3.10.0
      - kornia==0.7.2
      - scikit-image==0.20.0
