model = dict(
    config=dict(
        align_corners=True,
        coarse_branch=dict(
            align_corners=True,
            do_resize=False,
            fetch_features=True,
            force_keep_ar=True,
            freeze_midas_bn=True,
            img_size=[
                518,
                518,
            ],
            midas_model_type='vitl',
            pretrained_resource=None,
            train_midas=False,
            use_pretrained_midas=True,
            version='v2'),
        concat_dpt=True,
        encoder_type='vitl',
        gpct=True,
        freq_fusion=dict(
            in_channels=[
                32,
                256,
                256,
                256,
                256,
                256,
            ],
            n_channels=6,
            type='Fusion_freq_selective',
            wavelet='haar'),
        image_raw_shape=(
            2160,
            3840,
        ),
        is_loss=dict(
            data_loss=[
                'mse_loss',
            ],
            loss_weights=dict(mae_loss=1.0, mse_loss=4.0),
            type='ConsistencyLoss'),
        load_branch=True,
        loss=dict(
            align_corners=True,
            data_loss=[
                'mae_loss',
                'mse_loss',
            ],
            loss_weights=dict(
                grad_loss=5.0, mae_loss=1.0, mse_loss=1.0, weight_loss=2.0),
            scales=4,
            type='AffineInvariantLoss_dict_unrel'),
        max_depth=80,
        min_depth=0.001,
        overlap=(
            224,
            224,
        ),
        patch_process_shape=(
            518,
            518,
        ),
        patch_split_num=(
            4,
            4,
        ),
        pretrain_model=[
            './pretrained/Depth-Anything-V2/depth_anything_v2_vitl.pth'
        ],
        use_edgeintersect=True,
        use_unreliable_mask=True),
    type='PRO')
